import type { Option, Questionnaire, ScalePoint, Section } from '../types';

const opts = (...pairs: readonly (readonly [string, string, string?])[]): readonly Option[] =>
  pairs.map(([id, label, help]) => (help === undefined ? { id, label } : { id, label, help }));

export const ROLES = [
  { id: 'grower', label: 'Potato grower or business owner', pathway: 'farm' },
  { id: 'farm_manager', label: 'Farm manager, supervisor or machinery operator', pathway: 'farm' },
  { id: 'contractor', label: 'Contractor', pathway: 'contractor' },
  { id: 'processor', label: 'Processor, packhouse or storage business', pathway: 'processor' },
  { id: 'machinery', label: 'Machinery dealer, manufacturer or service provider', pathway: 'machinery' },
  { id: 'technology', label: 'Technology provider', pathway: 'technology' },
  { id: 'adviser', label: 'Adviser, consultant, researcher or educator', pathway: 'adviser' },
  { id: 'industry_body', label: 'Industry body or other stakeholder', pathway: 'adviser' },
] as const;

const REGIONS = opts(
  ['sa_murraylands', 'South Australia — Murraylands and Riverland'],
  ['sa_southeast', 'South Australia — South East and Adelaide Hills'],
  ['vic_ballarat', 'Victoria — Ballarat and Central Highlands'],
  ['vic_gippsland', 'Victoria — Gippsland'],
  ['vic_other', 'Victoria — other districts'],
  ['tas_north', 'Tasmania — North and North West'],
  ['tas_other', 'Tasmania — other districts'],
  ['nsw', 'New South Wales'],
  ['qld', 'Queensland — Lockyer Valley, Atherton and other districts'],
  ['wa', 'Western Australia'],
  ['national', 'National / multiple regions'],
  ['other', 'Other region'],
  ['no_say', 'Prefer not to say'],
);

const CONSTRAINTS = opts(
  ['field_prep', 'Field preparation and planting'],
  ['monitoring', 'Crop monitoring and decision support'],
  ['irrigation', 'Irrigation operation and automation'],
  ['crop_protection', 'Crop protection operations'],
  ['harvesting', 'Harvesting'],
  ['harvest_logistics', 'In-field transport and harvest logistics'],
  ['receival', 'Receival'],
  ['grading', 'Washing, grading and sorting'],
  ['packing', 'Packing'],
  ['storage', 'Storage and handling'],
  ['data', 'Data capture, traceability and system integration'],
  ['maintenance', 'Machinery maintenance and reliability'],
  ['skills', 'Access to skilled operators and technicians'],
  ['other', 'Other'],
);

const PRIORITY_SCALE: readonly ScalePoint[] = [
  { value: 1, label: 'Not a priority' },
  { value: 2, label: 'Low priority' },
  { value: 3, label: 'Moderate priority' },
  { value: 4, label: 'High priority' },
  { value: 5, label: 'Very high priority' },
];

const CORE: readonly Section[] = [
  {
    id: 'core_constraints',
    title: 'Where the pressure is',
    intro: 'These questions are about the industry as you see it, not only your own business.',
    questions: [
      {
        id: 'q1_constraints',
        kind: 'multi',
        prompt: 'Where do you see the biggest mechanisation, automation or workflow constraints in the potato industry?',
        help: 'Choose as many as apply.',
        options: CONSTRAINTS,
        allowOther: true,
      },
      {
        id: 'q2_top_three',
        kind: 'rank',
        prompt: 'Please select the three constraints that should receive the greatest attention.',
        help: 'Tap to add them in order. Your first choice counts as the most important.',
        count: 3,
        sourceQuestionId: 'q1_constraints',
        fallbackOptions: CONSTRAINTS,
      },
      {
        id: 'q3_impact',
        kind: 'multi',
        prompt: 'For the highest-priority constraint, what is the main business impact?',
        help: 'Choose as many as apply.',
        options: opts(
          ['labour_avail', 'Labour availability'],
          ['labour_cost', 'Labour cost'],
          ['timeliness', 'Timeliness of operations'],
          ['yield', 'Yield loss'],
          ['quality', 'Quality loss or reduced pack-out'],
          ['damage', 'Bruising, damage or handling loss'],
          ['whs', 'Workplace health and safety'],
          ['downtime', 'Machine downtime or reliability'],
          ['inputs', 'Energy, fuel or water use'],
          ['skills', 'Difficulty accessing skilled operators or technicians'],
          ['data', 'Lack of useful operational data'],
          ['other', 'Other'],
        ),
        allowOther: true,
      },
      {
        id: 'q4_bad_season',
        kind: 'text',
        prompt: 'In a difficult season or peak workload period, what happens if this issue is not addressed?',
        help: 'For example: delayed harvest, lower quality, reduced throughput, extra labour cost, crop loss, safety risk or lost market opportunity.',
        rows: 4,
      },
    ],
  },
  {
    id: 'core_priorities',
    title: 'What the project should look at',
    questions: [
      {
        id: 'q5_areas',
        kind: 'rating',
        prompt: 'Which areas should the Potato Mechanisation Project investigate or support first?',
        help: 'Rate each area from 1 (not a priority) to 5 (very high priority).',
        scale: PRIORITY_SCALE,
        rows: opts(
          ['precision_planting', 'Precision planting and crop establishment'],
          ['autonomy', 'Autonomous or semi-autonomous field operations', 'Machines that run with limited or no driver input.'],
          ['harvest_efficiency', 'Harvest efficiency and damage reduction'],
          ['harvest_logistics', 'Harvest logistics and transport coordination'],
          ['optical_sorting', 'Optical sorting, grading and quality measurement', 'Cameras and sensors that grade tubers as they pass.'],
          ['packhouse_automation', 'Packhouse and receival automation'],
          ['robotics', 'Robotics for repetitive manual tasks'],
          ['sensors', 'Sensors and machine data for operational decisions'],
          ['irrigation_automation', 'Irrigation automation linked to crop and soil information'],
          ['predictive_maintenance', 'Predictive maintenance and machinery uptime', 'Using machine data to service a part before it fails.'],
          ['interoperability', 'Data standards and system interoperability', 'Making equipment and software from different suppliers share data.'],
          ['training', 'Training, skills and workforce pathways'],
        ),
      },
      {
        id: 'q6_first_opportunities',
        kind: 'text',
        prompt: 'Which one or two opportunities should the project investigate first, and why?',
        rows: 4,
      },
      {
        id: 'q7_evidence',
        kind: 'multi',
        prompt: 'What type of evidence would give you confidence to trial or adopt a new mechanisation or automation option?',
        help: 'Choose as many as apply.',
        options: opts(
          ['local_demo', 'Local demonstration under Australian potato conditions'],
          ['roi', 'Independent economic analysis or ROI assessment', 'An independent look at whether the money spent comes back.'],
          ['operating_data', 'Practical operating data'],
          ['case_study', 'Case study from a similar business'],
          ['peer', 'Peer grower or industry experience'],
          ['service', 'Good local service, parts and technical support'],
          ['training', 'Training for operators and managers'],
          ['finance', 'Finance, leasing or ownership-model options'],
          ['safety', 'Clear safety or regulatory guidance'],
          ['compatibility', 'Better compatibility with existing equipment or data systems'],
          ['other', 'Other'],
        ),
        allowOther: true,
      },
    ],
  },
];

const ADOPTION_BARRIERS = opts(
  ['capital', 'Upfront capital cost'],
  ['roi', 'Uncertain return on investment'],
  ['reliability', 'Reliability or downtime concerns'],
  ['service', 'Lack of local service or support'],
  ['operators', 'Lack of suitable operators or training'],
  ['fit', 'Poor fit with existing systems'],
  ['evidence', 'Lack of evidence under Australian conditions'],
  ['data', 'Data or integration issues'],
  ['safety', 'Safety or regulatory concerns'],
  ['other', 'Other'],
);

const PATHWAYS: Readonly<Record<string, Section>> = {
  farm: {
    id: 'farm',
    title: 'Your farming operation',
    intro: 'A short set of questions about growing, farm management and machinery operation.',
    questions: [
      {
        id: 'farm_pressure',
        kind: 'text',
        prompt: 'Which parts of your farming operation have the most significant labour, timeliness, safety, quality or reliability pressures?',
        rows: 4,
      },
      {
        id: 'farm_adopted',
        kind: 'text',
        prompt: 'What machinery, automation or digital systems have you adopted, trialled or seriously considered?',
        rows: 4,
      },
      {
        id: 'farm_outcome',
        kind: 'single',
        prompt: 'For technologies trialled or considered, what was the outcome?',
        options: opts(
          ['expand', 'Working well and likely to expand'],
          ['refine', 'Working, but needs refinement'],
          ['stopped', 'Trialled but not continued'],
          ['not_adopted', 'Investigated but not adopted'],
          ['not_relevant', 'Not currently relevant'],
        ),
      },
      {
        id: 'farm_barriers',
        kind: 'multi',
        prompt: 'What has most limited adoption?',
        help: 'Choose as many as apply.',
        options: ADOPTION_BARRIERS,
        allowOther: true,
      },
      {
        id: 'farm_measures',
        kind: 'multi',
        prompt: 'Which measures matter most when assessing an investment?',
        help: 'Choose as many as apply.',
        options: opts(
          ['labour_hours', 'Labour hours saved'],
          ['cost_ha', 'Cost per hectare'],
          ['cost_t', 'Cost per tonne'],
          ['yield', 'Yield'],
          ['packout', 'Pack-out', 'The share of the crop that makes saleable grade.'],
          ['quality', 'Quality'],
          ['damage', 'Bruising or damage'],
          ['throughput', 'Throughput'],
          ['timeliness', 'Timeliness'],
          ['safety', 'Safety'],
          ['inputs', 'Water, fuel or energy use'],
          ['maintenance', 'Maintenance and downtime'],
          ['other', 'Other'],
        ),
        allowOther: true,
      },
      {
        id: 'farm_case_study',
        kind: 'text',
        prompt: 'Are there technologies currently in use that would make a useful local case study or demonstration?',
        rows: 3,
      },
      {
        id: 'farm_scepticism',
        kind: 'text',
        prompt: 'Is there a technology or practice being promoted that you think is unlikely to work well in Australian potato production? What is the concern?',
        rows: 3,
      },
    ],
  },
  contractor: {
    id: 'contractor',
    title: 'Contracting work',
    questions: [
      { id: 'con_peak', kind: 'text', prompt: 'What operations create the greatest pressure during peak periods?', rows: 3 },
      { id: 'con_limits', kind: 'text', prompt: 'What limits your ability to improve timeliness, throughput, labour efficiency or quality?', rows: 3 },
      { id: 'con_service', kind: 'text', prompt: 'What machinery reliability, parts availability or servicing issues matter most?', rows: 3 },
      { id: 'con_skills', kind: 'text', prompt: 'What operator skills or training gaps are most important?', rows: 3 },
      { id: 'con_tech', kind: 'text', prompt: 'Which technologies could improve contractor services to potato businesses?', rows: 3 },
      { id: 'con_demo', kind: 'text', prompt: 'What would be needed for a demonstration or trial to be commercially realistic?', rows: 3 },
    ],
  },
  processor: {
    id: 'processor',
    title: 'Receival, storage, grading and packing',
    questions: [
      {
        id: 'pro_constraints',
        kind: 'text',
        prompt: 'Where are the major labour, throughput, quality, handling or safety constraints in receival, storage, grading, sorting, packing or dispatch?',
        rows: 4,
      },
      { id: 'pro_losses', kind: 'text', prompt: 'Which losses or quality issues are most important to address?', rows: 3 },
      {
        id: 'pro_systems',
        kind: 'text',
        prompt: 'What automation, sensing, grading or data systems have been investigated, trialled or adopted?',
        rows: 3,
      },
      {
        id: 'pro_barriers',
        kind: 'multi',
        prompt: 'What has limited adoption or expansion?',
        help: 'Choose as many as apply.',
        options: ADOPTION_BARRIERS,
        allowOther: true,
      },
      {
        id: 'pro_measures',
        kind: 'multi',
        prompt: 'Which performance measures are most important?',
        help: 'Choose as many as apply.',
        options: opts(
          ['throughput', 'Throughput'],
          ['labour', 'Labour requirement'],
          ['grading_accuracy', 'Grading accuracy'],
          ['consistency', 'Quality consistency'],
          ['damage', 'Bruising and handling damage'],
          ['traceability', 'Traceability'],
          ['downtime', 'Downtime'],
          ['energy', 'Energy use'],
          ['food_safety', 'Food safety or compliance'],
          ['other', 'Other'],
        ),
        allowOther: true,
      },
      {
        id: 'pro_case_study',
        kind: 'text',
        prompt: 'What would make a project case study, demonstration or independent assessment valuable?',
        rows: 3,
      },
    ],
  },
  machinery: {
    id: 'machinery',
    title: 'Machinery supply and service',
    questions: [
      {
        id: 'mach_available',
        kind: 'text',
        prompt: 'What machinery or automation options are currently available or emerging for Australian potato businesses?',
        rows: 4,
      },
      { id: 'mach_ready', kind: 'text', prompt: 'Which technologies appear most commercially ready?', rows: 3 },
      {
        id: 'mach_barriers',
        kind: 'multi',
        prompt: 'What are the main barriers to adoption among potato businesses?',
        help: 'Choose as many as apply.',
        options: ADOPTION_BARRIERS,
        allowOther: true,
      },
      { id: 'mach_capacity', kind: 'text', prompt: 'What service, spare-parts, training or technical-support capacity is needed?', rows: 3 },
      {
        id: 'mach_gaps',
        kind: 'text',
        prompt: 'Where do you see gaps between available technology and on-farm or packhouse requirements?',
        rows: 3,
      },
      {
        id: 'mach_contribute',
        kind: 'single',
        prompt: 'Would you be interested in contributing to a demonstration, case study or technical briefing?',
        help: 'You can give contact details at the end if you would like to be approached about this.',
        options: opts(['yes', 'Yes'], ['maybe', 'Possibly, depending on the detail'], ['no', 'No']),
      },
    ],
  },
  technology: {
    id: 'technology',
    title: 'Your technology',
    intro: 'Please keep this to a level of detail you are comfortable sharing.',
    questions: [
      {
        id: 'tech_offer',
        kind: 'text',
        prompt: 'What technology or capability do you offer that may be relevant to potato production, harvesting, handling, processing or data management?',
        rows: 4,
      },
      { id: 'tech_problem', kind: 'text', prompt: 'What problem does the technology solve?', rows: 3 },
      {
        id: 'tech_maturity',
        kind: 'single',
        prompt: 'How mature is the technology?',
        options: opts(
          ['concept', 'Concept or prototype'],
          ['early', 'Early commercial trials'],
          ['overseas', 'Commercially available overseas'],
          ['au', 'Commercially available in Australia'],
          ['established', 'Established use in Australian potato systems'],
        ),
      },
      {
        id: 'tech_requirements',
        kind: 'text',
        prompt: 'What operating conditions, data, infrastructure or business processes are needed for successful implementation?',
        rows: 3,
      },
      {
        id: 'tech_evidence',
        kind: 'text',
        prompt: 'What evidence is available about performance, labour impacts, quality, cost or return on investment?',
        rows: 3,
      },
      { id: 'tech_demo', kind: 'text', prompt: 'What would be needed for a credible Australian demonstration or evaluation?', rows: 3 },
    ],
  },
  adviser: {
    id: 'adviser',
    title: 'Evidence, evaluation and extension',
    questions: [
      { id: 'adv_gaps', kind: 'text', prompt: 'What are the most important mechanisation knowledge or evidence gaps?', rows: 4 },
      { id: 'adv_evaluate', kind: 'text', prompt: 'What technologies or operational issues deserve independent evaluation?', rows: 3 },
      { id: 'adv_measurements', kind: 'text', prompt: 'What measurements should be included in a field or packhouse demonstration?', rows: 3 },
      { id: 'adv_underrepresented', kind: 'text', prompt: 'Which groups are currently underrepresented in mechanisation discussions?', rows: 3 },
      { id: 'adv_sharing', kind: 'text', prompt: 'What are the best ways to share findings so they are useful to potato businesses?', rows: 3 },
      {
        id: 'adv_connections',
        kind: 'text',
        prompt: 'Are there existing projects, research, data sources or demonstration sites the project should connect with?',
        rows: 3,
      },
    ],
  },
};

const PROJECT_DESIGN: readonly Section[] = [
  {
    id: 'project_design',
    title: 'How the project should work',
    questions: [
      {
        id: 'pd_most_useful',
        kind: 'text',
        prompt: 'What should the Potato Mechanisation Project do that would be most useful to your business or the wider industry?',
        rows: 4,
      },
      { id: 'pd_avoid', kind: 'text', prompt: 'What should the project avoid spending time or money on?', rows: 3 },
      {
        id: 'pd_formats',
        kind: 'multi',
        prompt: 'What information or engagement formats are most useful to you?',
        help: 'Choose as many as apply.',
        options: opts(
          ['case_studies', 'Short practical case studies'],
          ['videos', 'Videos from commercial operations'],
          ['field_demos', 'Field demonstrations'],
          ['peer_groups', 'Small peer groups'],
          ['webinars', 'Webinars'],
          ['briefings', 'Short online briefings'],
          ['checklists', 'Machinery or operator checklists'],
          ['roi_tools', 'ROI calculators and decision tools'],
          ['factsheets', 'Technical factsheets'],
          ['one_to_one', 'One-to-one discussions'],
          ['articles', 'PotatoLink articles or updates'],
          ['other', 'Other'],
        ),
        allowOther: true,
      },
      {
        id: 'pd_timing',
        kind: 'multi',
        prompt: 'When is the least disruptive time for you to participate in future online discussions, site visits or short consultations?',
        help: 'Choose as many as apply.',
        options: opts(
          ['early_am', 'Early morning'],
          ['late_am', 'Late morning'],
          ['afternoon', 'Afternoon'],
          ['evening', 'Evening'],
          ['off_peak', 'Outside peak production periods'],
          ['winter', 'During winter or the off-season'],
          ['other', 'Other'],
          ['no_say', 'Prefer not to say'],
        ),
        allowOther: true,
      },
    ],
  },
];

export const NO_INTEREST_ID = 'none';

export const INTEREST_OPTIONS = opts(
  ['follow_up', 'Confidential follow-up discussion'],
  ['summary', 'Receiving a summary of findings'],
  ['online_discussion', 'Joining a future online discussion'],
  ['peer_group', 'Participating in a small peer group'],
  ['demo', 'Hosting or participating in a field demonstration'],
  ['case_study', 'Contributing to a case study'],
  ['data', 'Contributing de-identified operational data'],
  ['review_tool', 'Reviewing a draft ROI or decision-support tool'],
  ['updates', 'Receiving PotatoLink updates about mechanisation'],
  [NO_INTEREST_ID, 'None of these'],
);

export const DEFAULT_QUESTIONNAIRE: Questionnaire = {
  roundId: '2026-round-1',
  roundLabel: 'PT25003 consultation, round 1',
  roles: ROLES,
  regions: REGIONS,
  core: CORE,
  pathways: PATHWAYS,
  projectDesign: PROJECT_DESIGN,
  interestOptions: INTEREST_OPTIONS,
  contactMethods: opts(['email', 'Email'], ['phone', 'Phone'], ['either', 'Either']),
};
